export const MOVIE_REQUEST = 'MOVIE_REQUEST';
export const MOVIE_SUCCESS = 'MOVIE_SUCCESS';
export const MOVIE_FAILURE = 'MOVIE_FAILURE';

export const CREDITS_REQUEST = 'CREDITS_REQUEST';
export const CREDITS_SUCCESS = 'CREDITS_SUCCESS';
export const CREDITS_FAILURE = 'CREDITS_FAILURE';

export const MOVIE_IMAGES_REQUEST = 'MOVIE_IMAGES_REQUEST';
export const MOVIE_IMAGES_SUCCESS = 'MOVIE_IMAGES_SUCCESS';
export const MOVIE_IMAGES_FAILURE = 'MOVIE_IMAGES_FAILURE';
