export const WATCHLIST_REQUEST = 'WATCHLIST_REQUEST';
export const WATCHLIST_SUCCESS = 'WATCHLIST_SUCCESS';
export const WATCHLIST_FAILURE = 'WATCHLIST_FAILURE';

export const ADD_TO_WATCHLIST_REQUEST = 'ADD_TO_WATCHLIST_REQUEST';
export const ADD_TO_WATCHLIST_SUCCESS = 'ADD_TO_WATCHLIST_SUCCESS';
export const ADD_TO_WATCHLIST_FAILURE = 'ADD_TO_WATCHLIST_FAILURE';
