export const CREATED_LISTS_REQUEST = 'CREATED_LISTS_REQUEST';
export const CREATED_LISTS_SUCCESS = 'CREATED_LISTS_SUCCESS';
export const CREATED_LISTS_FAILURE = 'CREATED_LISTS_FAILURE';

export const DETAILS_LIST_REQUEST = 'DETAILS_LIST_REQUEST';
export const DETAILS_LIST_SUCCESS = 'DETAILS_LIST_SUCCESS';
export const DETAILS_LIST_FAILURE = 'DETAILS_LIST_FAILURE';

export const CREATE_LIST_REQUEST = 'CREATE_LIST_REQUEST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILURE = 'CREATE_LIST_FAILURE';

export const DELETE_LIST_REQUEST = 'DELETE_LIST_REQUEST';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAILURE = 'DELETE_LIST_FAILURE';

export const ADD_MOVIE_LIST_REQUEST = 'ADD_MOVIE_LIST_REQUEST';
export const ADD_MOVIE_LIST_SUCCESS = 'ADD_MOVIE_LIST_SUCCESS';
export const ADD_MOVIE_LIST_FAILURE = 'ADD_MOVIE_LIST_FAILURE';

export const REMOVE_MOVIE_LIST_REQUEST = 'REMOVE_MOVIE_LIST_REQUEST';
export const REMOVE_MOVIE_LIST_SUCCESS = 'REMOVE_MOVIE_LIST_SUCCESS';
export const REMOVE_MOVIE_LIST_FAILURE = 'REMOVE_MOVIE_LIST_FAILURE';
