export const CREATED_LISTS_REQUEST = 'CREATED_LISTS_REQUEST';
export const CREATED_LISTS_SUCCESS = 'CREATED_LISTS_SUCCESS';
export const CREATED_LISTS_FAILURE = 'CREATED_LISTS_FAILURE';

export const DELETE_LIST_REQUEST = 'DELETE_LIST_REQUEST';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAILURE = 'DELETE_LIST_FAILURE';
