export const AUTH_ACCESS_REQUEST = 'AUTH_ACCESS_REQUEST';
export const AUTH_ACCESS_SUCCESS = 'AUTH_ACCESS_SUCCESS';
export const AUTH_ACCESS_FAILURE = 'AUTH_ACCESS_FAILURE';
export const AUTH_ACCESS_REMOVE = 'AUTH_ACCESS_REMOVE';
