export const ACCESS_REQUEST = 'ACCESS_REQUEST';
export const ACCESS_SUCCESS = 'ACCESS_SUCCESS';
export const ACCESS_FAILURE = 'ACCESS_FAILURE';

export const ACCESS_ADD = 'ACCESS_ADD';
export const ACCESS_REMOVE = 'ACCESS_REMOVE';
