export const FAVORITE_REQUEST = 'FAVORITE_REQUEST';
export const FAVORITE_SUCCESS = 'FAVORITE_SUCCESS';
export const FAVORITE_FAILURE = 'FAVORITE_FAILURE';

export const ADD_TO_FAVORITE_REQUEST = 'ADD_TO_FAVORITE_REQUEST';
export const ADD_TO_FAVORITE_SUCCESS = 'ADD_TO_FAVORITE_SUCCESS';
export const ADD_TO_FAVORITE_FAILURE = 'ADD_TO_FAVORITE_FAILURE';
