export const AUTH_GUEST_SESSION_REQUEST = 'AUTH_GUEST_SESSION_REQUEST';
export const AUTH_GUEST_SESSION_SUCCESS = 'AUTH_GUEST_SESSION_SUCCESS';
export const AUTH_GUEST_SESSION_FAILURE = 'AUTH_GUEST_SESSION_FAILURE';
