export default {
  CREATE_LIST_REQUEST: 'CREATE_LIST_REQUEST',
  CREATE_LIST_SUCCESS: 'CREATE_LIST_SUCCESS',
  CREATE_LIST_FAILURE: 'CREATE_LIST_FAILURE',

  ADD_MOVIE_REQUEST: 'ADD_MOVIE_REQUEST',
  ADD_MOVIE_SUCCESS: 'ADD_MOVIE_SUCCESS',
  ADD_MOVIE_FAILURE: 'ADD_MOVIE_FAILURE',
};
